# Pokemon IA (test)

## Import des modules
#### **(Et configuration du theme plt)**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import keras as ks

plt.rcParams['figure.facecolor'] = '#1A202C'
plt.rcParams['axes.facecolor'] = '#1A202C'  # Couleur de fond des axes
plt.rcParams['axes.edgecolor'] = '#FFFFFF'  # Couleur des bordures des axes
plt.rcParams['axes.labelcolor'] = '#FFFFFF'  # Couleur des étiquettes des axes
plt.rcParams['xtick.color'] = '#FFFFFF'  # Couleur des ticks sur l'axe des x
plt.rcParams['ytick.color'] = '#FFFFFF'  # Couleur des ticks sur l'axe des y
plt.rcParams['text.color'] = '#FFFFFF'

ModuleNotFoundError: No module named 'keras'

## Chargement du Pokedex (dataset)

In [15]:
pokedex = pd.read_csv("datas/pokemon/pokedex.csv")

## Analyse du dataset
### Affichage des données

In [25]:
pokedex

,NUMERO,NOM,TYPE_1,TYPE_2,POINTS_DE_VIE,POINTS_ATTAQUE,POINTS_DEFFENCE,POINTS_ATTAQUE_SPECIALE,POINT_DEFENSE_SPECIALE,POINTS_VITESSE,NOMBRE_GENERATIONS,LEGENDAIRE
0,1,Bulbizarre,Herbe,Poison,45,49,49,65,65,45,1,FAUX
1,2,Herbizarre,Herbe,Poison,60,62,63,80,80,60,1,FAUX
2,3,Florizarre,Herbe,Poison,80,82,83,100,100,80,1,FAUX
3,4,Mega Florizarre,Herbe,Poison,80,100,123,122,120,80,1,FAUX
4,5,SalamÃ¨che,Feu,NaN,39,52,43,60,50,65,1,FAUX
...,...,...,...,...,...,...,...,...,...,...,...,...
795,796,Diancie,Roche,FÃ©e,50,100,150,100,150,50,6,VRAI
796,797,Mega Diancie,Roche,FÃ©e,50,160,110,160,110,110,6,VRAI
797,798,Hoopa confinÃ©,Psy,Spectre,80,110,60,150,130,70,6,VRAI
798,799,Hoopa non liÃ©,Psy,Obscur,80,160,60,170,130,80,6,VRAI
799,800,Volcanion,Feu,Eau,80,110,120,130,90,70,6,VRAI

### Affichage des données manquantes

In [26]:
pokedex.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NUMERO                   800 non-null    int64
 1   NOM                      799 non-null    object
 2   TYPE_1                   800 non-null    object
 3   TYPE_2                   413 non-null    object
 4   POINTS_DE_VIE            800 non-null    int64
 5   POINTS_ATTAQUE           800 non-null    int64
 6   POINTS_DEFFENCE          800 non-null    int64
 7   POINTS_ATTAQUE_SPECIALE  800 non-null    int64
 8   POINT_DEFENSE_SPECIALE   800 non-null    int64
 9   POINTS_VITESSE           800 non-null    int64
 10  NOMBRE_GENERATIONS       800 non-null    int64
 11  LEGENDAIRE               800 non-null    object
dtypes: int64(8), object(4)
memory usage: 75.1+ KB

### Description des données

In [20]:
pokedex.describe()

,NUMERO,POINTS_DE_VIE,POINTS_ATTAQUE,POINTS_DEFFENCE,POINTS_ATTAQUE_SPECIALE,POINT_DEFENSE_SPECIALE,POINTS_VITESSE,NOMBRE_GENERATIONS
count,800.0000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,400.5000,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,231.0844,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.0000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,200.7500,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,400.5000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,600.2500,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,800.0000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000